In [3]:
import pandas as pd
import numpy as np

In [4]:
#Task 1. Importing All Dependencies
df = pd.read_csv('provider_info.csv')

In [5]:
#1st five rows
df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,0,11,0,NaN,8,8,NaN,12,11,NaN
1,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,0,8,1,NaN,8,8,NaN,12,12,NaN
2,10006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,0,8,1,NaN,8,8,NaN,12,10,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,0,NaN,8,8,NaN,12,7,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,Acute Care Hospitals,Proprietary,...,0,2,0,NaN,8,Not Available,5.0,12,6,NaN

In [7]:
# last 5 rows
df.tail()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
5421,670781,ANSON GENERAL HOSPITAL,101 AVENUE J,ANSON,TX,79501,JONES,(325) 823-3231,Rural Emergency Hospital,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,19.0,Not Available,Not Available,19.0,Not Available,Not Available,19.0
5422,670783,CHI ST LUKES HEALTH MEMORIAL SAN AUGUSTINE,511 HOSPITAL ST,SAN AUGUSTINE,TX,75972,SAN AUGUSTINE,(936) 275-3446,Rural Emergency Hospital,Voluntary non-profit - Private,...,Not Available,Not Available,Not Available,19.0,Not Available,Not Available,19.0,Not Available,Not Available,19.0
5423,671300,GRAHAM REGIONAL MEDICAL CENTER,1301 MONTGOMERY ROAD,GRAHAM,TX,76450,YOUNG,(940) 549-3400,Critical Access Hospitals,Government - Hospital District or Authority,...,0,3,0,NaN,8,Not Available,5.0,12,5,NaN
5424,671301,HEMPHILL COUNTY HOSPITAL,1020 S 4TH ST,CANADIAN,TX,79014,HEMPHILL,(806) 323-6622,Critical Access Hospitals,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,5.0,8,Not Available,5.0,12,2,NaN
5425,671302,STEPHENS MEMORIAL HOSPITAL,200 SOUTH GENEVA STREET,BRECKENRIDGE,TX,76424,STEPHENS,(254) 559-2241,Critical Access Hospitals,Government - Hospital District or Authority,...,Not Available,Not Available,Not Available,5.0,Not Available,Not Available,5.0,Not Available,Not Available,5.0