In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
# loading datasets
df = pd.read_csv('Inpatient_payments.csv')
df.head()

,Rndrng_Prvdr_CCN,Rndrng_Prvdr_Org_Name,Rndrng_Prvdr_City,Rndrng_Prvdr_St,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_RUCA,Rndrng_Prvdr_RUCA_Desc,DRG_Cd,DRG_Desc,Tot_Dschrgs,Avg_Submtd_Cvrd_Chrg,Avg_Tot_Pymt_Amt,Avg_Mdcr_Pymt_Amt
0,10001,Southeast Alabama Medical Center,Dothan,1108 Ross Clark Circle,1,36301,AL,1.0,Metropolitan area core: primary flow within an...,23,CRANIOTOMY WITH MAJOR DEVICE IMPLANT OR ACUTE ...,32,126083.18750,26993.156250,25320.750000
1,10001,Southeast Alabama Medical Center,Dothan,1108 Ross Clark Circle,1,36301,AL,1.0,Metropolitan area core: primary flow within an...,25,CRANIOTOMY AND ENDOVASCULAR INTRACRANIAL PROCE...,31,115948.41940,21662.225810,20814.032260
2,10001,Southeast Alabama Medical Center,Dothan,1108 Ross Clark Circle,1,36301,AL,1.0,Metropolitan area core: primary flow within an...,37,EXTRACRANIAL PROCEDURES WITH MCC,13,78837.30769,16666.615390,14301.230770
3,10001,Southeast Alabama Medical Center,Dothan,1108 Ross Clark Circle,1,36301,AL,1.0,Metropolitan area core: primary flow within an...,38,EXTRACRANIAL PROCEDURES WITH CC,17,56492.82353,8577.000000,6767.470588
4,10001,Southeast Alabama Medical Center,Dothan,1108 Ross Clark Circle,1,36301,AL,1.0,Metropolitan area core: primary flow within an...,39,EXTRACRANIAL PROCEDURES WITHOUT CC/MCC,51,45253.01961,6094.803922,4985.235294

In [10]:
df.tail()

,Rndrng_Prvdr_CCN,Rndrng_Prvdr_Org_Name,Rndrng_Prvdr_City,Rndrng_Prvdr_St,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_RUCA,Rndrng_Prvdr_RUCA_Desc,DRG_Cd,DRG_Desc,Tot_Dschrgs,Avg_Submtd_Cvrd_Chrg,Avg_Tot_Pymt_Amt,Avg_Mdcr_Pymt_Amt
196081,670122,Houston Methodist The Woodlands Hospital,The Woodlands,17201 Interstate 45 South,48,77385,TX,1.1,Secondary flow 30% to <50% to a larger urbaniz...,470,MAJOR HIP AND KNEE JOINT REPLACEMENT OR REATTA...,65,110888.64620,12491.338460,10468.676920
196082,670122,Houston Methodist The Woodlands Hospital,The Woodlands,17201 Interstate 45 South,48,77385,TX,1.1,Secondary flow 30% to <50% to a larger urbaniz...,483,MAJOR JOINT OR LIMB REATTACHMENT PROCEDURES OF...,14,119134.28570,13972.571430,12844.571430
196083,670122,Houston Methodist The Woodlands Hospital,The Woodlands,17201 Interstate 45 South,48,77385,TX,1.1,Secondary flow 30% to <50% to a larger urbaniz...,603,CELLULITIS WITHOUT MCC,12,35154.00000,5057.333333,3824.833333
196084,670122,Houston Methodist The Woodlands Hospital,The Woodlands,17201 Interstate 45 South,48,77385,TX,1.1,Secondary flow 30% to <50% to a larger urbaniz...,690,KIDNEY AND URINARY TRACT INFECTIONS WITHOUT MCC,11,32644.54546,4424.909091,3707.090909
196085,670122,Houston Methodist The Woodlands Hospital,The Woodlands,17201 Interstate 45 South,48,77385,TX,1.1,Secondary flow 30% to <50% to a larger urbaniz...,871,SEPTICEMIA OR SEVERE SEPSIS WITHOUT MV >96 HOU...,45,69184.37778,10245.755560,9573.133333

In [11]:
df.shape

(196086, 15)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196086 entries, 0 to 196085
Data columns (total 15 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Rndrng_Prvdr_CCN           196086 non-null  int64
 1   Rndrng_Prvdr_Org_Name      196086 non-null  object
 2   Rndrng_Prvdr_City          196086 non-null  object
 3   Rndrng_Prvdr_St            196086 non-null  object
 4   Rndrng_Prvdr_State_FIPS    196086 non-null  int64
 5   Rndrng_Prvdr_Zip5          196086 non-null  int64
 6   Rndrng_Prvdr_State_Abrvtn  196086 non-null  object
 7   Rndrng_Prvdr_RUCA          196050 non-null  float64
 8   Rndrng_Prvdr_RUCA_Desc     196050 non-null  object
 9   DRG_Cd                     196086 non-null  int64
 10  DRG_Desc                   196086 non-null  object
 11  Tot_Dschrgs                196086 non-null  int64
 12  Avg_Submtd_Cvrd_Chrg       196086 non-null  float64
 13  Avg_Tot_Pymt_Amt           196086 non-null  float64
 14  Avg_Mdcr_Pymt_Amt          196086 non-null  float64
dtypes: float64(4), int64(5), object(6)
memory usage: 22.4+ MB

In [ ]:
# Statistical Summary
df.describe()

,Rndrng_Prvdr_CCN,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_RUCA,DRG_Cd,Tot_Dschrgs,Avg_Submtd_Cvrd_Chrg,Avg_Tot_Pymt_Amt,Avg_Mdcr_Pymt_Amt
count,196086.000000,196086.000000,196086.000000,196050.000000,196086.000000,196086.000000,1.960860e+05,196086.000000,196086.000000
mean,255922.434070,27.999847,47389.769662,1.896193,413.573891,37.728981,6.199726e+04,14119.214838,11915.514312
std,151556.749381,15.395457,28020.919591,6.645062,248.128752,57.771411,7.422644e+04,14982.957554,13298.194873
min,10001.000000,1.000000,1040.000000,1.000000,1.000000,11.000000,2.941444e+03,2570.650000,240.086957
25%,110074.000000,13.000000,25401.000000,1.000000,216.000000,14.000000,2.442467e+04,6596.901581,5202.622650
50%,240115.000000,27.000000,44106.000000,1.000000,371.000000,21.000000,4.067010e+04,9761.211905,8120.066964
75%,380022.000000,41.000000,72401.000000,1.000000,605.000000,39.000000,7.181262e+04,15654.109250,13173.815475
max,670122.000000,56.000000,99801.000000,99.000000,989.000000,4291.000000,3.362417e+06,612054.050000,569811.000000

In [17]:
# data cleaning 

df.isnull().sum()
df.dropna(inplace=True)
df.isnull().sum()

Rndrng_Prvdr_CCN             0
Rndrng_Prvdr_Org_Name        0
Rndrng_Prvdr_City            0
Rndrng_Prvdr_St              0
Rndrng_Prvdr_State_FIPS      0
Rndrng_Prvdr_Zip5            0
Rndrng_Prvdr_State_Abrvtn    0
Rndrng_Prvdr_RUCA            0
Rndrng_Prvdr_RUCA_Desc       0
DRG_Cd                       0
DRG_Desc                     0
Tot_Dschrgs                  0
Avg_Submtd_Cvrd_Chrg         0
Avg_Tot_Pymt_Amt             0
Avg_Mdcr_Pymt_Amt            0
dtype: int64

In [19]:
# dealing with duplicates rows
df.duplicated().sum()

# deleting all duplicated rows
# data[data.duplicated()]

df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [ ]:
# type casting 
# changing data types 
df.dtypes

Rndrng_Prvdr_CCN               int64
Rndrng_Prvdr_Org_Name         object
Rndrng_Prvdr_City             object
Rndrng_Prvdr_St               object
Rndrng_Prvdr_State_FIPS        int64
Rndrng_Prvdr_Zip5              int64
Rndrng_Prvdr_State_Abrvtn     object
Rndrng_Prvdr_RUCA            float64
Rndrng_Prvdr_RUCA_Desc        object
DRG_Cd                         int64
DRG_Desc                      object
Tot_Dschrgs                    int64
Avg_Submtd_Cvrd_Chrg         float64
Avg_Tot_Pymt_Amt             float64
Avg_Mdcr_Pymt_Amt            float64
dtype: object

ValueError: Could not interpret value `Avg_Tot_Pymt_Amt` for `x`. Value is a string, but `data` was not passed.